version: '3'

services:
  db:
    image: mysql:8.0
    command: ["mysqld", "--lower-case-table-names=1"]
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lotsa2
      MYSQL_USER: lotsa_user
      MYSQL_PASSWORD: password
    ports:
      - '3333:3306'
    volumes:
      - ./dockercache/mysqldata:/var/lib/mysql

